### ISSUE TITLE
no windows walllet

### ISSUE THREAD

**Issue by cantu12** [GreenDoge-Network/greendoge-blockchain#1]
another shit launch with no client for windows, only for linux "experts", not fair at all, go to hell... hehehe

**Comment by grayfallstown** [comment]
To be more precise, the daemon folder on Windows only contains a file `fix_it_does_not_exist` and not the greendoge executable or start_farmer.exe, or start_wallet.exe, it only contains the GUI, none of the functionality.

**Comment by lionethan** [comment]
I have started the release windows exe and installer in version 1.0.0.
