### ISSUE TITLE
[BUG] Error on create transaction

### ISSUE THREAD

**Issue by eks500** [GreenDoge-Network/greendoge-blockchain#11]
**Describe the bug**
When I try to create a transaction from my wallet to other GreenDoge wallet created on other PC gui throws an error:

![image](https://user-images.githubusercontent.com/47854326/125263981-c1c12600-e303-11eb-8816-736a559814bc.png)

**To Reproduce**
Try to create a transaction to other wallet address

**Expected behavior**
Create the transaction succesfully.

**Desktop (please complete the following information):**

- OS: Windows 10
- CPU: Ryzen 3600

**Additional context**
I'm mining many forks at the same time (chia, flax, spare, chaingreen, rosechain, goji, silicon)

**Comment by lionethan** [comment]
It has been fixed.
