### ISSUE TITLE
[BUG] 1.0.0 Windows: No functionality executables, only the GUI is included - which does not work without start_full_node.exe and the others

### ISSUE THREAD

**Issue by grayfallstown** [GreenDoge-Network/greendoge-blockchain#2]
**Describe the bug**
greendoge.exe, start_farmer.exe, start_full_node.exe, and so on are all missing from the daemon folder. The folder only contains a file called `fix_it_does_not_exist`

**To Reproduce**

1. Install on Windows
2. Try to use greendoge from GUI or CLI, both does not work

**Expected behavior**
Greendoge comes with all executable necessary to run it

**Additional context**
The Installation file is about 50MB smaller than of the previous release, about the size of all the executables and library files that are missing.

**Comment by lionethan** [comment]
What you said should be version 1.0.1. I will recompile the new version to solve the bug.
