### ISSUE TITLE
[BUG] Support of new “Portable” NFT ploters

### ISSUE THREAD

**Issue by arturotrenard** [GreenDoge-Network/greendoge-blockchain#58]
Hello on the Chia Forks page they indicate that they have full support for the new NFT plots but it is not like that. I have been harvesting for two weeks now and I only receive 2.5 GDOG reward and not the 20 GDOG offered. So my question for you would be. When do you start adding full support for the new NFT plotters? Thanks a lot

**Comment by lionethan** [comment]
That is not a bug. If you assign plots to a Chia plot NFT instead of a GreenDoge plot NFT, you will only get 1/8 rewards now. When you can get all the rewards using Chia plot NFT, we will announce it.
