### ISSUE TITLE
[BUG]1.2.7 GreenDoge Infected!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by olgyan93btc** [GreenDoge-Network/greendoge-blockchain#68]
Hi,
Last version is infected by Trojan:Win32/Wacatac.B!m.

?????????????

**Comment by lionethan** [comment]
It is a false detection, please refer to the following link:
https://www.virustotal.com/gui/file/7864facee04408304a27de40936e56625a2dec868c989cea21b78b52f2ab5371
